import streamlit as st

# -*- coding: utf-8 -*-
"""Ube Crinkle Cookies

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nijx_7POInQveeOEUcSC1KuWYH-Dbo0
"""

recipe_name = "Ube Crinkle Cookies"
servings = 18

ingredients = [
    "1 ¾ cups all-purpose flour",
    "1 tsp baking powder",
    "¼ teaspoon kosher salt",
    "1 cup granulated sugar",
    "½  cup unsalted butter",
    "1 large egg",
    "½ cup ube halaya jam",
    "2 teaspoons ube extract",
    "½ teaspoon pure vanilla extract",
    "1 cup confectioners' sugar"]

print("=" * 40)
print(f"  {recipe_name}")
print(f"  Servings: {servings}")
print("=" * 40)
print("\nINGREDIENTS:")
for item in ingredients:
    print(f"  - {item}")
print("=" * 40)

Instructions = [
    "Preheat oven to 350°F.",
    "In a bowl wisk together the flour, baking powder, and salt",
    "In another bowl combine the sugar and butter and beat until light and fluffy.",
    "Add egg and beat until combined.",
    "Add the ube halaya jam, ube extract, and vanilla extract. Beat until combined and completely purple.",
    "Gradually add the dry ingredients and beat until just combined.",
    "Chill overnight",
    "Roll into 3 tbs balls and coat generolly with confectioners’ sugar.",
    "Bake cookies for 12 to 15 minutes."]

print("\nInstructions:")
for i, Instructions in enumerate(Instructions, start=1):
    print(f"  {i}. {Instructions}")

print("=" * 40)

flour_price  = 0.03 # per oz (Great Value)
baking_power_price = 0.262 # per oz (Great Value)
salt_price = 0.139 # per oz (Morton)
granlated_sugar_price = 0.049 # per oz (Great Value)
unsalted_butter_price = 0.279 # per oz (Land O Lakes)
egg_price = 0.121 # per egg (Great Value)
ube_halaya_jam_price = 0.90 # per oz (Florence)
ube_extract_price = 0.845 # per oz (Butterfly)
vanilla_extract_price = 3.00 # per oz (Great Value)
confectioners_sugar_price = 0.062 # per oz (Great Value)

OzFlour = 4.25
OzBakingPowder = 0.167
OzSalt = 0.2
OzGranulatedSugar = 7
OzUnsaltedButter = 8.0
OzUbeHalayaJam = 9.5
OzUbeExtract = 0.17
OzVanillaExtract = 0.17
OzConfectionersSugar = 4

# Cost for what the recipe actually uses
cost_flour = 1.75 * OzFlour * flour_price
cost_baking_powder = 1 * OzBakingPowder * baking_power_price
cost_salt = 0.25 * OzSalt * salt_price
cost_granulated_sugar = 1 * OzGranulatedSugar * granlated_sugar_price
cost_butter = 0.5 * OzUnsaltedButter * unsalted_butter_price
cost_egg = egg_price
cost_ube_jam = 0.5 * OzUbeHalayaJam * ube_halaya_jam_price
cost_ube_extract = 2 * OzUbeExtract * ube_extract_price
cost_vanilla_extract = 0.5 * OzVanillaExtract * vanilla_extract_price
cost_confectioners_sugar = 1 * OzConfectionersSugar * confectioners_sugar_price

total_cost = cost_flour + cost_baking_powder + cost_salt + cost_granulated_sugar + cost_egg + cost_ube_jam + cost_ube_extract + cost_vanilla_extract + cost_confectioners_sugar

cost_per_roll = total_cost / 18

print(f"Total recipe cost: ${total_cost:.2f}")
print(f"Cost per cookie: ${cost_per_roll:.2f}")

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

ube_total_cost = cost_flour + cost_baking_powder + cost_salt + cost_granulated_sugar + cost_egg + cost_ube_jam + cost_ube_extract + cost_vanilla_extract + cost_confectioners_sugar
ube_base_servings = 18
ube_cost_per_cookie = ube_total_cost / ube_base_servings

def show_ube_card(desired_cookies):
    scale = desired_cookies / ube_base_servings

    html = f"""
    <div style="
        background: #f5f0ff;
        border-radius: 15px;
        padding: 25px;
        max-width: 400px;
        font-family: Arial, sans-serif;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    ">
        <h2 style="color: #6b21a8;">🍪 Ube Crinkle Cookies</h2>
        <p style="color: #888;">Recipe for <b>{desired_cookies} cookies</b></p>
        <hr>
        <h4 style="color: #6b21a8;">Ingredients</h4>
        <ul>
            <li>{1.75 * scale:.2f} cups all-purpose flour</li>
            <li>{1 * scale:.2f} tsp baking powder</li>
            <li>{0.25 * scale:.2f} tsp kosher salt</li>
            <li>{1 * scale:.2f} cups granulated sugar</li>
            <li>{0.5 * scale:.2f} cups unsalted butter</li>
            <li>{1 * scale:.1f} large egg(s)</li>
            <li>{0.5 * scale:.2f} cups ube halaya jam</li>
            <li>{2 * scale:.2f} tsp ube extract</li>
            <li>{0.5 * scale:.2f} tsp pure vanilla extract</li>
            <li>{1 * scale:.2f} cups confectioners sugar</li>
        </ul>
        <hr>
        <h4 style="color: #6b21a8;">Instructions</h4>
        <ol>
            <li>Preheat oven to 350°F.</li>
            <li>In a bowl whisk together the flour, baking powder, and salt.</li>
            <li>In another bowl combine the sugar and butter and beat until light and fluffy.</li>
            <li>Add egg and beat until combined.</li>
            <li>Add the ube halaya jam, ube extract, and vanilla extract. Beat until completely purple.</li>
            <li>Gradually add the dry ingredients and beat until just combined.</li>
            <li>Chill overnight.</li>
            <li>Roll into 3 tbsp balls and coat generously with confectioners sugar.</li>
            <li>Bake for 12-15 minutes.</li>
        </ol>
        <hr>
        <p>💰 Total cost: <b>${ube_total_cost * scale:.2f}</b></p>
        <p>🍪 Cost per cookie: <b>${ube_cost_per_cookie:.2f}</b></p>
    </div>
    """
    display(HTML(html))

# Input box and button
cookie_input = widgets.IntText(value=18, description='Cookies:')
button = widgets.Button(description='Calculate!', button_style='warning')

def on_click(b):
    clear_output(wait=True)
    display(cookie_input, button)
    show_ube_card(cookie_input.value)

button.on_click(on_click)
display(cookie_input, button)
